Допустим, у нас есть $n$ товаров с заданными стоимостями $v_i$ и массой $w_i$. В сумку убирается $С$ кг. Сколько какого товара взять, чтобы сумма всех стоимостей товаров была наибольшей?

In [1]:
values = [4, 2, 1, 7, 3, 6]
weights = [5, 9, 8, 2, 6, 5]
C = 15
n = 6

Сформулируем задачу:
$$\max\sum v_i x_i$$
$$\sum w_i x_i \leq C $$

Как должна выглядеть задача:
$$\min c^T x$$
$$A x \leq b $$

Получается, что $c=-v$, $A=w^T$, $b=(C)$

In [2]:
import numpy as np

In [3]:
c = - np.array(values)
A = np.array(weights)         #shape = (6,)
A = np.expand_dims(A, 0)      #shape = (1,6)
b = np.array([C])

In [4]:
from scipy.optimize import linprog

In [5]:
linprog(c=c, A_ub=A, b_ub=b)

     con: array([], dtype=float64)
     fun: -52.50000000003077
 message: 'Optimization terminated successfully.'
     nit: 5
   slack: array([-2.2495783e-11])
  status: 0
 success: True
       x: array([6.18738532e-14, 1.05853306e-12, 1.21475943e-13, 7.50000000e+00,
       4.00246692e-13, 4.71394162e-13])

In [6]:
!pip install cvxpy

     |████████████████████████████████| 2.7 MB 1.6 MB/s eta 0:00:01
     |████████████████████████████████| 6.6 MB 2.5 MB/s eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 126 kB 3.2 MB/s eta 0:00:01
     |████████████████████████████████| 215 kB 3.0 MB/s eta 0:00:01
     |████████████████████████████████| 921 kB 3.2 MB/s eta 0:00:01
  Created wheel for ecos: filename=ecos-2.0.7.post1-cp38-cp38-linux_x86_64.whl size=235378 sha256=57ce5b29581ac3786b6e226e67370c28cc73ab3be9a5d79fd017da9b169bd638
  Stored in directory: /home/fktr0/.cache/pip/wheels/c3/c1/ce/b551b0b3a40c990e1da2ec9aecff62f7c2d43cab8766368e82
  Created wheel for scs: filename=scs-2.1.4-cp38-cp38-linux_x86_64.whl size=578319 sha256=9e6e73d1f8cf8e015077b437a03dee76ca8d687c8edd0a6f19c70d9aa5338b61
  Stored in directory: /home/fktr0/.cache/pip/wheels/f9/1b/79/5e399d671778e7a7770bc72053a60cac6c0a2abc3

In [13]:
import cvxpy

In [14]:
x = cvxpy.Variable(shape=n, integer = True)

In [15]:
constraint = (A @ x <= b)
total_value = c * x

In [16]:
problem = cvxpy.Problem(cvxpy.Minimize(total_value), constraints=[constraint])

In [17]:
problem.solve()

-138412039.0000002

In [18]:
x.value

array([ 8388608.00000001, -8388608.00000001, -8388608.00000001,
        8388608.00000001,  6990509.00000001,  8388608.00000001])

Теперь положительные $x$

In [19]:
x = cvxpy.Variable(shape=n, integer=True)
constraint = (A @ x <= b)
x_positive = (x >= 0)
total_value = c * x
problem = cvxpy.Problem(cvxpy.Minimize(total_value), constraints=[constraint, x_positive])
problem.solve()

-49.000000015906025

In [20]:
x.value

array([7.01265807e-10, 7.99333027e-10, 3.58703130e-10, 7.00000000e+00,
       4.67143021e-10, 9.34955115e-10])

Теперь $x = 0$ или $1$

In [21]:
x = cvxpy.Variable(shape=n, boolean=True)
constraint = A @ x <= b
x_positive = x >= 0
total_value = c * x
problem = cvxpy.Problem(cvxpy.Minimize(total_value), constraints=[constraint, x_positive])
problem.solve()

-17.00000000382157

In [22]:
x.value

array([1.00000000e+00, 2.25474413e-10, 2.07396078e-10, 1.00000000e+00,
       2.24003299e-10, 1.00000000e+00])

In [7]:
x = cvxpy.Variable(shape=n, integer=True)
constraint = (A @ x <= b)
x_positive = (x >= 0)
total_value = c * x
problem = cvxpy.Problem(cvxpy.Minimize(total_value), constraints=[constraint, x_positive])
problem.solve()

NameError: name 'cvxpy' is not defined