In [29]:
import numpy as np

In [30]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [31]:
A

array([[ 5, 10,  8],
       [ 5,  5,  5],
       [10,  8, 11]])

In [32]:
B

array([[ 2, -2,  2],
       [ 3,  3,  0],
       [-1, -2, -1]])

In [33]:
# Поэлементное умножение
A*B

array([[ 10, -20,  16],
       [ 15,  15,   0],
       [-10, -16, -11]])

In [34]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[ 32   4   2]
 [ 20  -5   5]
 [ 33 -18   9]]


In [35]:
# Матричное умножение
np.dot(A,B)

array([[ 32,   4,   2],
       [ 20,  -5,   5],
       [ 33, -18,   9]])

In [36]:
# Матричное умножение
A@B

array([[ 32,   4,   2],
       [ 20,  -5,   5],
       [ 33, -18,   9]])

In [37]:
# Порядок умножения AB != BA
B@A

array([[ 20,  26,  28],
       [ 30,  45,  39],
       [-25, -28, -29]])

In [38]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[ 9  6  8  7  5]
 [10  6  8 10  7]
 [11  6  8  8  5]]
B:
 [[-1  1]
 [ 2 -2]
 [ 3  2]
 [-1 -2]
 [-2  0]]


In [39]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[10, -1],
       [ 2, -6],
       [ 7, -1]])

In [40]:
# Умножение прямоугольных матриц возможно не в любом порядке
# B@A

In [41]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [42]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[-1  3 -1  1]
 [ 3  1  2 -4]
 [-4  1  3  2]
 [ 1 -1 -2 -4]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[-1  6  0 -1]
 [ 3  2  0  4]
 [-4  2  0 -2]
 [ 1 -2  0  4]]
DA:
 [[-1  3 -1  1]
 [ 6  2  4 -8]
 [ 0  0  0  0]
 [-1  1  2  4]]


In [43]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [44]:
# b@A

In [45]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [46]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [47]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [48]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[ 1.00000000e+00, -1.77961928e-17,  1.66584120e-17],
       [-1.77961928e-17,  1.00000000e+00, -2.45142679e-17],
       [ 1.66584120e-17, -2.45142679e-17,  1.00000000e+00]])

In [49]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])