In [2]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4])

In [3]:
arr2 = np.array([5,6,7,8], dtype = float)
arr2.dtype

dtype('float64')

In [4]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
np.shape(arr3)
Out: (3, 3)

In [7]:
import numpy as np
import pandas as pd

df = pd.DataFrame()
x = df.values
type(x)

numpy.ndarray

In [8]:
import numpy as np
import pandas as pd
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series.values

array([ 5,  6,  7,  8,  9, 10], dtype=int64)

In [9]:
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована
np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 
np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 
np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3
np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14
np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7
np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно
np.random.randint(0, 10, (3, 3))  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 10

array([[0, 5, 8],
       [8, 9, 7],
       [7, 8, 9]])

In [19]:
np.empty(5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [22]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [15]:
np.arange(0, 21, 7)

array([ 0,  7, 14])

In [17]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
[x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]

[1, 57, 71, 127, 141, 197, 211, 267, 281]

In [21]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.array([i for i in range(11) if i%2])

array([1, 3, 5, 7, 9])

In [27]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [28]:
np.array(range(9))

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
my_array = np.array([x for x in range(10)])

In [34]:
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
my_array[5]

5

In [31]:
my_array[-1]

9

In [32]:
my_array[3:6]

array([3, 4, 5])

In [33]:
my_array[1:8:3]

array([1, 4, 7])

In [35]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])

In [36]:
my_array[1][2]

12

In [37]:
my_array[1,2]

12

In [85]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

In [86]:
big_secret

array([[1.40000000e+01, 1.00000000e+01, 6.00000000e+00, 5.60000000e+01,
        4.00000000e+01, 2.40000000e+01, 9.80000000e+01, 7.00000000e+01,
        4.20000000e+01, 1.40000000e+02, 1.00000000e+02, 6.00000000e+01,
        1.82000000e+02, 1.30000000e+02, 7.80000000e+01, 2.24000000e+02,
        1.60000000e+02, 9.60000000e+01, 2.66000000e+02, 1.90000000e+02,
        1.14000000e+02, 3.08000000e+02, 2.20000000e+02, 1.32000000e+02,
        3.50000000e+02, 2.50000000e+02, 1.50000000e+02, 3.92000000e+02,
        2.80000000e+02, 1.68000000e+02, 4.34000000e+02, 3.10000000e+02,
        1.86000000e+02, 4.76000000e+02, 3.40000000e+02, 2.04000000e+02,
        5.18000000e+02, 3.70000000e+02, 2.22000000e+02, 5.60000000e+02,
        4.00000000e+02, 2.40000000e+02, 6.02000000e+02, 4.30000000e+02,
        2.58000000e+02, 6.44000000e+02, 4.60000000e+02, 2.76000000e+02,
        6.86000000e+02, 4.90000000e+02, 2.94000000e+02],
       [3.16227766e+01, 3.16543836e+01, 3.16859590e+01, 3.17175031e+01,
       

In [45]:
print(len(first_line))
print(len(second_line))
print(len(third_line))

51
51
51


In [48]:
gg = 0
for i in big_secret:
    gg += i[-1]
round(gg,2)

3154.33

In [123]:
n = 0
gg = 0
for i in big_secret:
    print(i[:5])
    gg += i[:5][n]
    n += 1
round(gg,2)

[-1. 10. -1. 56. -1.]
[31.6227766   1.         31.68595904  1.         31.74901573]
[-1.  1. -1.  9. -1.]
[31.6227766   1.         31.68595904  1.         31.74901573]
[-1. 10. -1. 56. -1.]


-1.0

In [124]:
n = 0
#gg = big_secret[0][-5]
gg = 0
for i in big_secret:
    if n == 0:
        gg = i[-5:][n]
    else:
        gg *= i[-5:][n]
    
    n += 1
round(gg,2)

-1.0

In [96]:
for i in big_secret:
    print(i[-5:])


[460. 276. 686. 490. 294.]
[33.04542328 33.07567082 33.10589071 33.13608305 33.1662479 ]
[2116. 2209. 2304. 2401. 2500.]
[33.04542328 33.07567082 33.10589071 33.13608305 33.1662479 ]
[460. 276. 686. 490. 294.]


In [100]:
my_array = np.random.randint(1, 100, (4, 6)) 

In [101]:
my_array

array([[69, 92, 95, 15, 21, 92],
       [ 9, 70, 87, 50, 19, 50],
       [ 3, 90, 72,  7, 18, 55],
       [45, 90,  1, 47, 84, 10]])

In [102]:
my_slice = my_array[1:3, 2:4]

In [103]:
my_slice

array([[87, 50],
       [72,  7]])

In [104]:
my_slice[:] = 0

In [105]:
my_array

array([[69, 92, 95, 15, 21, 92],
       [ 9, 70,  0,  0, 19, 50],
       [ 3, 90,  0,  0, 18, 55],
       [45, 90,  1, 47, 84, 10]])

In [118]:
for n,i in enumerate(big_secret):
    #print(i)
    print(n)
    for h,k in enumerate(i):
        #print(k)
        print(h)
        if n % 2 == 0 and h % 2 == 0:
            big_secret[n,h] = -1
        elif  n % 2 == 1 and h % 2 == 1:
            big_secret[n,h] = 1

0
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
1
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
2
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
3
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
4
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50


In [119]:
for n,i in enumerate(big_secret):
    for h,k in enumerate(i):
        print(big_secret[n,h])

-1.0
10.0
-1.0
56.0
-1.0
24.0
-1.0
70.0
-1.0
140.0
-1.0
60.0
-1.0
130.0
-1.0
224.0
-1.0
96.0
-1.0
190.0
-1.0
308.0
-1.0
132.0
-1.0
250.0
-1.0
392.0
-1.0
168.0
-1.0
310.0
-1.0
476.0
-1.0
204.0
-1.0
370.0
-1.0
560.0
-1.0
240.0
-1.0
430.0
-1.0
644.0
-1.0
276.0
-1.0
490.0
-1.0
31.622776601683793
1.0
31.68595903550972
1.0
31.74901573277509
1.0
31.811947441173732
1.0
31.874754901018456
1.0
31.937438845342623
1.0
32.0
1.0
32.0624390837628
1.0
32.12475680841802
1.0
32.18695387886216
1.0
32.2490309931942
1.0
32.31098884280702
1.0
32.37282811247729
1.0
32.43454948045371
1.0
32.49615361854384
1.0
32.55764119219941
1.0
32.61901286060018
1.0
32.68026927673638
1.0
32.7414110874898
1.0
32.802438933713454
1.0
32.863353450309965
1.0
32.92415526630866
1.0
32.984845004941285
1.0
33.04542328371661
1.0
33.1058907144937
1.0
33.166247903554
-1.0
1.0
-1.0
9.0
-1.0
25.0
-1.0
49.0
-1.0
81.0
-1.0
121.0
-1.0
169.0
-1.0
225.0
-1.0
289.0
-1.0
361.0
-1.0
441.0
-1.0
529.0
-1.0
625.0
-1.0
729.0
-1.0
841.0
-1.0
961.0
-

In [120]:
big_secret

array([[-1.00000000e+00,  1.00000000e+01, -1.00000000e+00,
         5.60000000e+01, -1.00000000e+00,  2.40000000e+01,
        -1.00000000e+00,  7.00000000e+01, -1.00000000e+00,
         1.40000000e+02, -1.00000000e+00,  6.00000000e+01,
        -1.00000000e+00,  1.30000000e+02, -1.00000000e+00,
         2.24000000e+02, -1.00000000e+00,  9.60000000e+01,
        -1.00000000e+00,  1.90000000e+02, -1.00000000e+00,
         3.08000000e+02, -1.00000000e+00,  1.32000000e+02,
        -1.00000000e+00,  2.50000000e+02, -1.00000000e+00,
         3.92000000e+02, -1.00000000e+00,  1.68000000e+02,
        -1.00000000e+00,  3.10000000e+02, -1.00000000e+00,
         4.76000000e+02, -1.00000000e+00,  2.04000000e+02,
        -1.00000000e+00,  3.70000000e+02, -1.00000000e+00,
         5.60000000e+02, -1.00000000e+00,  2.40000000e+02,
        -1.00000000e+00,  4.30000000e+02, -1.00000000e+00,
         6.44000000e+02, -1.00000000e+00,  2.76000000e+02,
        -1.00000000e+00,  4.90000000e+02, -1.00000000e+0

In [125]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format(result1, result2, result3, result4, result5))

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


In [126]:
my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
my_array.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [128]:
my_array = np.random.randint(0, 10, 20)
my_array.reshape((4,5))

array([[5, 2, 8, 3, 4],
       [3, 9, 8, 2, 5],
       [2, 1, 8, 7, 2],
       [5, 3, 5, 4, 7]])

In [129]:
my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])
my_array.flatten()

array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

In [130]:
my_array = np.random.randint(0, 10, (3,4))

In [131]:
my_array

array([[5, 2, 7, 2],
       [1, 4, 1, 5],
       [7, 9, 9, 4]])

In [132]:
my_array<5

array([[False,  True, False,  True],
       [ True,  True,  True, False],
       [False, False, False,  True]])

In [133]:
my_array[my_array<5]

array([2, 2, 1, 4, 1, 4])

In [134]:
mask = np.array([1, 0, 1, 0], dtype=bool)
my_array[:, mask]

array([[5, 7],
       [1, 1],
       [7, 9]])

In [135]:
my_array = np.random.randint(0, 10, (4, 6))

In [136]:
my_array

array([[9, 7, 5, 6, 4, 9],
       [4, 1, 9, 9, 3, 7],
       [4, 9, 4, 1, 8, 9],
       [4, 2, 5, 5, 8, 5]])

In [137]:
np.sort(my_array, axis=1)

array([[4, 5, 6, 7, 9, 9],
       [1, 3, 4, 7, 9, 9],
       [1, 4, 4, 8, 9, 9],
       [2, 4, 5, 5, 5, 8]])

In [138]:
np.sort(my_array, axis=0)

array([[4, 1, 4, 1, 3, 5],
       [4, 2, 5, 5, 4, 7],
       [4, 7, 5, 6, 8, 9],
       [9, 9, 9, 9, 8, 9]])

Функция	Описание
abs	Абсолютное значение целых, вещественных или комплексных элементов массива
sqrt	Квадратный корень каждого элемента массива
exp	Экспонента (ex) каждого элемента массива
log, log10, log2, log1p	Натуральный (по основанию е), десятичный, двоичный логарифм и функция log(1+x) соответственно
modf	Дробные и целые части массива в виде отдельных массивов
isnan	Массив логических (булевых) значений, показывающий, какие из элементов исходного массива  являются NaN (не числами)
cos, sin, tan	Обычные тригонометрические функции
arccos, arcsin, arctan	Обратные тригонометрические функции

In [139]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

In [143]:
np.cos(great_secret[0]).sum()

0.16006721889793019

In [148]:
great_secret[great_secret>50].sum()

5470.0

In [152]:
great_secret.flatten()[150]

7.0710678118654755

In [157]:
np.sort(great_secret, axis=0)[-1].sum()

115.12148016521353

In [6]:
students = np.array(
[[1,135,34,4],
[2,160,43,5],
[3,163,40,4.3],
[4,147,44,5],
[5,138,41,4.7],
[6,149,54,3.9],
[7,136,39,4.2],
[8,154,48,4.9],
[9,137,35,3.7],
[10,165,60,4.6]])

In [11]:
students[:,-1]


array([4. , 5. , 4.3, 5. , 4.7, 3.9, 4.2, 4.9, 3.7, 4.6])

In [7]:
mean = np.mean(students[:,-1])
mean

4.430000000000001

In [13]:
median = np.median(students[:,-1])
median


4.449999999999999

In [14]:
sort = np.sort(students[:,-1])
(sort[4]+sort[5])/2

4.449999999999999

In [15]:
median = np.median(students[:,-2])
median


42.0

In [16]:
mean = np.mean(students[:,-2])
median - mean

-1.7999999999999972

In [19]:
corr = np.corrcoef(students[:,2], students[:,3])
corr

array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

In [20]:
std = np.std(students[:,1])
std

11.083320801997928

In [21]:
std = np.std(students[:,-1])
std

0.4517742799230607

In [23]:
var = np.var(students[:,-2])
var

60.36

In [49]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])

In [50]:
my_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [27]:
my_array[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [51]:
my_sin = np.sin(my_array)

In [32]:
round(my_sin,3)

-0.058

In [38]:
my_sin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [67]:
my_sin[1:4,1:4] = 1.0

In [41]:
round(my_sin.sum(),3)

7.572

In [43]:
my_sin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  1.        ,  1.        ,  1.        , -0.54402111],
       [-0.99999021,  1.        ,  1.        ,  1.        ,  0.65028784],
       [-0.28790332,  1.        ,  1.        ,  1.        ,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [68]:
my_sin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  1.        ,  1.        ,  1.        , -0.54402111],
       [-0.99999021,  1.        ,  1.        ,  1.        ,  0.65028784],
       [-0.28790332,  1.        ,  1.        ,  1.        ,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [69]:
my_sin[:,:-1].reshape((10,2))[:,0].sum()

2.4057172058139544

In [59]:
round(my_sin[0].sum(),3)

0.176

In [74]:
bigdata = np.arange(101, 1000, 2)**2
np.std(bigdata)

292095.0301991155

In [75]:
np.corrcoef(bigdata[0::2], bigdata[1::2]) 

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])

In [77]:
6*6*6

216

In [82]:
0.5*0.5*0.5*0.5*0.5

0.03125

In [85]:
k = 0.5
for i in range(9):
    k *= 0.5
k

0.0009765625

In [81]:
0.5/10

0.05

In [ ]:
1/2

In [3]:
print(np.__version__)

1.19.2


In [4]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/user/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/user/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/user/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/user/anaconda3\\Library\\include']


In [5]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
Z = np.arange(50)
Z = Z[::-1]

In [7]:
Z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [8]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [18]:
Z = np.ones((10,10))
Z[1:-1,1:-1]=0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [19]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

In [20]:
0 * np.nan

nan

In [21]:
np.nan == np.nan

False

In [22]:
np.inf > np.nan

False

In [23]:
np.nan - np.nan

nan

In [24]:
0.3 == 3 * 0.1

False

In [25]:
3 * 0.1

0.30000000000000004

In [27]:
Z = np.diag(np.arange(1, 5), k=1)
print(Z)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [33]:
Z = np.zeros((8,8), dtype=int)
Z[::2,::2]=1
Z[1::2,1::2]=1
print(Z)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [34]:
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [35]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)
